apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-sqlinj-demo
  namespace: vuln-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuln-sqlinj-demo
  template:
    metadata:
      labels:
        app: vuln-sqlinj-demo
    spec:
      containers:
        - name: app
          image: docker.io/ashmitathapar/vuln-sqlinj-demo:3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
