apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-sqlinj-demo
  namespace: vuln-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuln-sqlinj-demo
  template:
    metadata:
      labels:
        app: vuln-sqlinj-demo
    spec:
      containers:
        - name: app
          image: docker.io/ashmitathapar/vuln-sqlinj-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/accounts?owner=Alice
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/accounts?owner=Alice
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
