apiVersion: v1
kind: Service
metadata:
  name: vuln-sqlinj-demo-svc
  namespace: vuln-demo
spec:
  selector:
    app: vuln-sqlinj-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
